-- Migration: 012_table_qr
-- Customer QR per table. Each table gets a secret qr_token (generated by the
-- app the first time the QR is shown); scanning it opens /t.php?k=<token>,
-- where the guest sees the table's order and can ask for the bill, call the
-- waiter or ask for a change to a dish. Each ask is a table_request that the
-- staff see live in their own area until it is taken and done.

ALTER TABLE tables_restaurant
    ADD COLUMN qr_token VARCHAR(40) NULL DEFAULT NULL,
    ADD UNIQUE INDEX uq_tables_qr_token (qr_token);

CREATE TABLE IF NOT EXISTS table_requests (
    id             INT AUTO_INCREMENT PRIMARY KEY,
    table_id       INT NOT NULL,
    order_id       INT NULL DEFAULT NULL,
    order_item_id  INT NULL DEFAULT NULL,
    type           ENUM('bill', 'waiter', 'change') NOT NULL,
    message        VARCHAR(300) NULL DEFAULT NULL,
    status         ENUM('open', 'seen', 'done') NOT NULL DEFAULT 'open',
    seen_by        INT NULL DEFAULT NULL,
    seen_at        TIMESTAMP NULL DEFAULT NULL,
    done_by        INT NULL DEFAULT NULL,
    done_at        TIMESTAMP NULL DEFAULT NULL,
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_table_requests_status (status, created_at),
    INDEX idx_table_requests_table (table_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
